### ISSUE TITLE
can't find the module w2j

### ISSUE THREAD

**Issue by supotnitskiy** [zrong/wiz2joplin#1]
Thank you very much for this project.

I have an operating system Ubuntu 20.04.2 LTS

can't find the module w2j

> python3 joplin.py
> Traceback (most recent call last):
> File "joplin.py", line 16, in <module>
> from w2j import logger
> ModuleNotFoundError: No module named 'w2j'

**Comment by zrong** [comment]
The root module is w2j, so you CANNOT use `python3 joplin.py`.

You can read the [test case](https://github.com/zrong/wiz2joplin/tree/master/tests) to find how to use the tool.

I will wite a README later.

If you can read chinese, pls read this: https://blog.zengrong.net/post/wiznote2joplin2/

**Comment by zrong** [comment]
[README](https://github.com/zrong/wiz2joplin/blob/master/README.md) has been updated.
