### ISSUE TITLE
关于转换遇到找不到文件的问题反馈

### ISSUE THREAD

**Issue by lutery** [zrong/wiz2joplin#10]
采了些坑，留下一点使用过程中遇到的问题以及解决办法反馈

遇到最多的问题应该就是找不到文件了

实际上确实是文件已经丢失，这个是无解
为什么？因为存在很多markdown文档在引用图片的时候，使用的是URL链接，如果一旦URL链接失效后，这个图片就找不到了，使用本工具转换时，由于没有考虑到这种情况，所以一旦遇到失效的链接，就会报错。

可以通过源码debug可以定位到具体的文档名称，找到那份有问题的文档，将其中失效的链接去除或者替换，然后删除临时数据库，重新重头开始迁移即可。

其实可以考虑添加一个遇到错误继续的迁移的功能，然后在迁移完成后输出有报错的文章，去定位修改即可

**Comment by zrong** [comment]
> 

不知道你有空提一个 PR 么？我在转换的时候没有碰到这样的例子，貌似好多碰到此类问题的同学都是在 Windows 版本下出现的。
