### ISSUE TITLE
notes are not converted 

### ISSUE THREAD

**Issue by supotnitskiy** [zrong/wiz2joplin#3]
all work is carried out under the operating system ubuntu 20.20

python3.9 --version
`_`Python 3.9.2`_`

### work with a profile wiznote created by the program under linux

on first try to start

w2j -o ~/w2j -w ~/.wiznote -u supotnitskiy@gmail.com -t 40cf6fba7c626d539fbdb606e****** -a

```
Please read [/home/sergei/w2j/w2j.log] to check the conversion states.
Traceback (most recent call last):
  File "/home/sergei/w2j/venv/bin/w2j", line 33, in <module>
    sys.exit(load_entry_point('w2j==0.4', 'console_scripts', 'w2j')())
  File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/__init__.py", line 64, in main
    ws = wiz.WizStorage(args.wiz_user, wiznote_dir, is_group_storage=False, work_dir=output_dir)
  File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/wiz.py", line 366, in __init__
    root_data_dir = DataDir(self.user_dir.joinpath('data/'))
  File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/wiz.py", line 216, in __init__
    raise FileNotFoundError(f'找不到文件夹 {self.attachments_dir.resolve()}！')
FileNotFoundError: 找不到文件夹 /home/sergei/.wiznote/supotnitskiy@gmail.com/data/attachments！
```

i created a missing folder 

mkdir /home/sergei/.wiznote/supotnitskiy@gmail.com/data/attachments
 

then started again 

```
Please read [/home/sergei/w2j/w2j.log] to check the conversion states.
Traceback (most recent call last):
  File "/home/sergei/w2j/venv/bin/w2j", line 33, in <module>
    sys.exit(load_entry_point('w2j==0.4', 'console_scripts', 'w2j')())
  File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/__init__.py", line 65, in main
    ad = adapter.Adapter(ws, jda, work_dir=output_dir)
  File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/adapter.py", line 413, in __init__
    self.ws.resolve()
  File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/wiz.py", line 478, in resolve
    self.documents = self.build_documents()
  File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/wiz.py", line 447, in build_documents
    document = WizDocument(*row, self.data_dir.notes_dir, self.documents_dir, check_file=True)
  File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/wiz.py", line 146, in __init__
    self.check_note_file()
  File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/wiz.py", line 150, in check_note_file
    raise FileNotFoundError(f'找不到 note 文件 {self.note_file}！')
FileNotFoundError: 找不到 note 文件 /home/sergei/.wiznote/supotnitskiy@gmail.com/data/notes/{d266fd52-8ff8-4efa-9ea5-b4298ca762bd}！
```

for some reason he is looking for a note that is there, but there are 1710 other notes 

ls  /home/sergei/.wiznote/supotnitskiy@gmail.com/data/notes/\{
`Display all 1710 possibilities? (y or n)`

here is the contents of the directories 

**ls -1 .wiznote/**
```
log
supotnitskiy@gmail.com
templates
wiznote.ini
```

**ls -1 .wiznote/supotnitskiy@gmail.com/**
```
analyzerEx.ini
analyzer.ini
data
wiznote.ini
```
**ls -1 .wiznote/supotnitskiy@gmail.com/**
```
analyzerEx.ini  analyzer.ini    data/           wiznote.ini
```
**ls -1 .wiznote/supotnitskiy@gmail.com/data/**
```
attachments
export.py
html2pdf.py
index.db
lib
LICENSE
notes
README.md
WizNotes
wizthumb.db
```

**ls -1 .wiznote/supotnitskiy@gmail.com/data/notes/**

```
{ff7fc16d-6f0c-04aa-2a3f-6b7f852ccb82}
{ff8094ad-9af2-463e-81da-36a293b13f4c}
{ff98f274-72ff-4673-80fb-4f828b32e88e}
{ff9a678d-3a35-4f60-956a-d31195969c8c}
{fff4e091-90a9-4ad5-8bdf-1bb7d43a33f2}
***************************************
```

then I don’t know what to do? 

### work with a profile wiznote created by the program under windows and then copied to  linux

w2j -o ~/w2j -w /media/DISK3/wiznote_base/ -u supotnitskiy@gmail.com -t 40cf6fba7c626d539fbd****** -a
```
Please read [/home/sergei/w2j/w2j.log] to check the conversion states.
Traceback (most recent call last):
File "/home/sergei/w2j/venv/bin/w2j", line 33, in <module>
sys.exit(load_entry_point('w2j==0.4', 'console_scripts', 'w2j')())
File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/__init__.py", line 64, in main
ws = wiz.WizStorage(args.wiz_user, wiznote_dir, is_group_storage=False, work_dir=output_dir)
File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/wiz.py", line 366, in __init__
root_data_dir = DataDir(self.user_dir.joinpath('data/'))
File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/wiz.py", line 216, in __init__
raise FileNotFoundError(f'找不到文件夹 {self.attachments_dir.resolve()}！')
FileNotFoundError: 找不到文件夹 /media/DISK3/wiznote_base/supotnitskiy@gmail.com/data/attachments！
```

here is the contents of the directories 

**ls /media/DISK3/wiznote_base/**
```
Backup  Data  dumps  Photos  Plugins  plugin_settings.ini  temp  templates  toolbars.xml  Update_x86  WizChromeBrowser.log  Wiz.log  Wiz.xml
```

**ls /media/DISK3/wiznote_base/Data/**
```
supotnitskiy@gmail.com
```

**ls -1 /media/DISK3/wiznote_base/Data/supotnitskiy@gmail.com/**
```
Config.ini
'Deleted Items'
GTD
index.db
index.db.backup
'My Drafts'
'My Emails'
'My Journals'
'My Notes'
'My Sticky Notes'
'My Tasks'
OffcialTemplatesRecord.json
quick_search.ini
repair_index.db
thumb.db
wizfolder.ini
английский
'воспитание детей'
'врачи и лечение'
дом
'жизненные советы'
задачи
инструменты
история
'компьютерные заметки'
купить
личное
люберцы
магазины
'покупка квартиры'
'полезная информация'
политика
православие
рецепты
сбербанк
скачать
сортировать
спорт
фмбц
храмы
юмор
```
 
 
It can be seen that the folder location is slightly different in the windows version. I decided to remake them for linux version 

ls -1 /media/DISK3/wiznote_base_copy/
Backup
dumps
Photos
Plugins
plugin_settings.ini
supotnitskiy@gmail.com
temp
templates
toolbars.xml
Update_x86
WizChromeBrowser.log
Wiz.log
Wiz.xml

Data renamed to  data

ls -1 /media/DISK3/wiznote_base_copy/supotnitskiy@gmail.com/
`data`

(venv) sergei@sergei-dom:~$ ls -1 /media/DISK3/wiznote_base_copy/supotnitskiy@gmail.com/data/
```
Config.ini
'Deleted Items'
GTD
index.db
index.db.backup
'My Drafts'
'My Emails'
'My Journals'
'My Notes'
'My Sticky Notes'
'My Tasks'
OffcialTemplatesRecord.json
quick_search.ini
repair_index.db
thumb.db
wizfolder.ini
английский
'воспитание детей'
'врачи и лечение'
дом
'жизненные советы'
задачи
инструменты
история
'компьютерные заметки'
купить
личное
люберцы
магазины
'покупка квартиры'
'полезная информация'
политика
православие
рецепты
сбербанк
скачать
сортировать
спорт
фмбц
храмы
юмор
```

mkdir /media/DISK3/wiznote_base_copy/supotnitskiy@gmail.com/data/attachments

mkdir /media/DISK3/wiznote_base_copy/supotnitskiy@gmail.com/data/notes

and added some notes to this folder 

ls -1 /media/DISK3/wiznote_base_copy/supotnitskiy@gmail.com/data/notes/
```
'Как проехать к Матушке Матроне.ziw'
Контакты.ziw
'Контакты - Иоанно-Предтеченский женский монастырь-.ziw'
'Контакты храма святых бессребреников Космы и Дамиа.ziw'
'Матрона московская.ziw'
'Москва Зачатьевский монастырь.ziw'
'Храм в честь иконы Божией Матери «Знамение»  в Пер.ziw'
'храм Илии Пророка в Обыденском переулке.ziw'
'Храм Казанской иконы Божией Матери- Котельники.ziw'
'Храм Святых Апостолов Петра и Павла у Яузских воро.ziw'
'Храм Успения Пресвятой Богородицы в Жилине.ziw'
'Храм Успения Пресвятой Богородицы в Путинках.ziw'
```

w2j -o ~/w2j -w /media/DISK3/wiznote_base_copy/ -u supotnitskiy@gmail.com -t 40cf6fba7c626d539fbdb606e*** -a
```
Please read [/home/sergei/w2j/w2j.log] to check the conversion states.
Traceback (most recent call last):
File "/home/sergei/w2j/venv/bin/w2j", line 33, in <module>
sys.exit(load_entry_point('w2j==0.4', 'console_scripts', 'w2j')())
File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/__init__.py", line 64, in main
ws = wiz.WizStorage(args.wiz_user, wiznote_dir, is_group_storage=False, work_dir=output_dir)
File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/wiz.py", line 366, in __init__
root_data_dir = DataDir(self.user_dir.joinpath('data/'))
File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/wiz.py", line 228, in __init__
raise FileNotFoundError(f'找不到数据库 {self.wizthumb_db.resolve()}！')
FileNotFoundError: 找不到数据库 /media/DISK3/wiznote_base_copy/supotnitskiy@gmail.com/data/wizthumb.db！
```

wizthumb.db  - I didn't have it (in windows profile). I took it from the linux profile 

w2j -o ~/w2j -w /media/DISK3/wiznote_base_copy/ -u supotnitskiy@gmail.com -t 40cf6fba7c626d539fbd***** -a

```
Please read [/home/sergei/w2j/w2j.log] to check the conversion states.
Traceback (most recent call last):
File "/home/sergei/w2j/venv/bin/w2j", line 33, in <module>
sys.exit(load_entry_point('w2j==0.4', 'console_scripts', 'w2j')())
File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/__init__.py", line 65, in main
ad = adapter.Adapter(ws, jda, work_dir=output_dir)
File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/adapter.py", line 413, in __init__
self.ws.resolve()
File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/wiz.py", line 478, in resolve
self.documents = self.build_documents()
File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/wiz.py", line 447, in build_documents
document = WizDocument(*row, self.data_dir.notes_dir, self.documents_dir, check_file=True)
File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/wiz.py", line 146, in __init__
self.check_note_file()
File "/home/sergei/w2j/venv/lib/python3.9/site-packages/w2j/wiz.py", line 150, in check_note_file
raise FileNotFoundError(f'找不到 note 文件 {self.note_file}！')
FileNotFoundError: 找不到 note 文件 /media/DISK3/wiznote_base_copy/supotnitskiy@gmail.com/data/notes/{d266fd52-8ff8-4efa-9ea5-b4298ca762bd}！
```
 
 
 
 Everywhere this note comes out  **d266fd52-8ff8-4efa-9ea5-b4298ca762bd**

advise what to do?

**Comment by supotnitskiy** [comment]
Many thanks to the author of the program.


I managed to solve the problem from the Linux profile. The whole problem was not complete synchronization wiznote. When I started syncing several times, it finally synced.

Some of the articles were postponed, but one article had a failure. The tags were also not transferred.

On failure, I will create a separate topic

**Comment by zrong** [comment]
Congratulations!

**Comment by codering** [comment]
遇到同样的问题，没看到怎么解决。。。

**Comment by zrong** [comment]
> 遇到同样的问题，没看到怎么解决。。。

原文的意思是他没有同步完成，缺少信息，所以会报错。

**Comment by nopia-alexander** [comment]
Hi, I have the same problem. There is no such folders in there \My Knowledge\Data\username@mail.ru\
There are already folders with notes and that files:
21.08.2021  17:21         2 969 600 index.db
21.08.2021  17:21            32 768 index.db-shm
21.08.2021  17:21         3 045 520 index.db-wal
21.08.2021  17:21         3 235 840 index.db.backup
21.08.2021  17:21               226 OffcialTemplatesRecord.json
21.08.2021  17:21         2 966 528 repair_index.db
09.08.2021  17:31        33 689 600 thumb.db
21.08.2021  17:21            32 768 thumb.db-shm
21.08.2021  17:21                 0 thumb.db-wal
so even if I create data\notes and data\attachments the script doesn't work 
And more of that I can`t complete sync since my trial period has expired and wiznote ask for 9$ per year for it

**Comment by Onefabis** [comment]
Hi, I have the same problem. There is no such folders in there \My Knowledge\Data\username@mail.ru
There are already folders with notes and that files:
21.08.2021 17:21 2 969 600 index.db
21.08.2021 17:21 32 768 index.db-shm
21.08.2021 17:21 3 045 520 index.db-wal
21.08.2021 17:21 3 235 840 index.db.backup
21.08.2021 17:21 226 OffcialTemplatesRecord.json
21.08.2021 17:21 2 966 528 repair_index.db
09.08.2021 17:31 33 689 600 thumb.db
21.08.2021 17:21 32 768 thumb.db-shm
21.08.2021 17:21 0 thumb.db-wal
so even if I create data\notes and data\attachments the script doesn't work
And more of that I can`t complete sync since my trial period has expired and wiznote ask for 9$ per year for it

**Comment by abe520** [comment]
@Onefabis Try to use this [wiznoteplus](https://github.com/altairwei/WizNotePlus) client to log in to the official account, and then use this tool to convert
